### ISSUE TITLE
Error: Algorithm "sha1"  not supported. supported values: passthrough

### ISSUE THREAD

**Issue by ccorcos** [MoOx/eslint-loader#128]
```
Module build failed: Error: Algorithm "sha1"  not supported. supported values: passthrough
  at applyDefaults (/Users/chet/Code/doug/packages/doug/node_modules/object-hash/index.js:89:11)
  at objectHash (/Users/chet/Code/doug/packages/doug/node_modules/object-hash/index.js:31:13)
  at Object.module.exports (/Users/chet/Code/doug/packages/doug/node_modules/eslint-loader/index.js:155:20)
```

No idea what this is all about. Any ideas? I'm using Yarn if that makes a difference...

**Comment by wrakky** [comment]
What operating system and version of node are you using? The error appears to be the node crypto module not having any hashes to use (including sha1). Do you get any output when running `crypto.getHashes()` in the node interactive shell?

**Comment by ccorcos** [comment]
All seems to be good. I'm on OS X Yosemite.

```
~ ❯❯❯ node --version
v6.3.1
~ ❯❯❯ node
> crypto.getHashes()
[ 'DSA',
  'DSA-SHA',
  'DSA-SHA1',
  'DSA-SHA1-old',
  'RSA-MD4',
  'RSA-MD5',
  'RSA-MDC2',
  'RSA-RIPEMD160',
  'RSA-SHA',
  'RSA-SHA1',
  'RSA-SHA1-2',
  'RSA-SHA224',
  'RSA-SHA256',
  'RSA-SHA384',
  'RSA-SHA512',
  'dsaEncryption',
  'dsaWithSHA',
  'dsaWithSHA1',
  'dss1',
  'ecdsa-with-SHA1',
  'md4',
  'md4WithRSAEncryption',
  'md5',
  'md5WithRSAEncryption',
  'mdc2',
  'mdc2WithRSA',
  'ripemd',
  'ripemd160',
  'ripemd160WithRSA',
  'rmd160',
  'sha',
  'sha1',
  'sha1WithRSAEncryption',
  'sha224',
  'sha224WithRSAEncryption',
  'sha256',
  'sha256WithRSAEncryption',
  'sha384',
  'sha384WithRSAEncryption',
  'sha512',
  'sha512WithRSAEncryption',
  'shaWithRSAEncryption',
  'ssl2-md5',
  'ssl3-md5',
  'ssl3-sha1',
  'whirlpool' ]
```

**Comment by MoOx** [comment]
I guess this is more an ``object-hash`` issue?

**Comment by ccorcos** [comment]
Perhaps... I really have no idea either. I'll let you know if I figure it out though.

**Comment by ccorcos** [comment]
figured it out here https://github.com/puleos/object-hash/issues/41
