### ISSUE TITLE
`Emitted value instead of an instance of Error` on WARNING under webpack 2.4.1

### ISSUE THREAD

**Issue by sompylasar** [MoOx/eslint-loader#172]
eslint-loader 1.7.1
webpack 2.4.1

Likely this happens:
https://github.com/webpack/webpack/blob/e2bb2f41fa9f74f063043249dfc9c06ea6d08c03/lib/NormalModule.js#L113-L115
```js
class NonErrorEmittedError extends WebpackError {
	constructor(error) {
		super();

		this.name = "NonErrorEmittedError";
		this.message = "(Emitted value instead of an instance of Error) " + error;

		Error.captureStackTrace(this, this.constructor);
	}
}

// ...

	createLoaderContext(resolver, options, compilation, fs) {
		const loaderContext = {
			version: 2,
			emitWarning: (warning) => {
				if(!(warning instanceof Error))
					warning = new NonErrorEmittedError(warning);
				this.warnings.push(new ModuleWarning(this, warning));
			},
			emitError: (error) => {
				if(!(error instanceof Error))
					error = new NonErrorEmittedError(error);
				this.errors.push(new ModuleError(this, error));
			},
```

**Comment by sompylasar** [comment]
@MoOx Maybe `webpack.version` isn't strictly `2` anymore?
```
emitter(webpack.version === 2 ?
```
Or even has never been...
@jaridmargolin

**Comment by sompylasar** [comment]
No, I'm blind, it's `2` right there in the `loaderContext`. https://github.com/webpack/webpack/blob/e2bb2f41fa9f74f063043249dfc9c06ea6d08c03/lib/NormalModule.js#L111 (which in `eslint-loader` code for some reason is called "webpack" and commented "webpack instance").

**Comment by senseluo** [comment]
same here, my configuration is the same as @sompylasar 

"eslint-loader": "^1.7.1",
"webpack": "^2.4.1"

**Comment by jaridmargolin** [comment]
Hmmm. I am not seeing the behavior on my end. @sompylasar @senseluo would either of you be able to create a standalone repo showing the error? I'd be happy to pull it down and look into it.

**Comment by sompylasar** [comment]
Looks like it's not `eslint-loader`'s fault. I've printed a stack of where this happens, and it's `happypack`:
```
       at Object.loaderContext.emitWarning (/__CENSORED__/node_modules/webpack/lib/NormalModule.js:112:71)
       at Object.LOADER_RPCS.emitWarning (/__CENSORED__/node_modules/happypack/lib/HappyRPCHandler.js:79:12)
       at HappyRPCHandler.execute (/__CENSORED__/node_modules/happypack/lib/HappyRPCHandler.js:56:22)
       at ChildProcess.acceptMessageFromWorker (/__CENSORED__/node_modules/happypack/lib/HappyThread.js:83:27)
       at emitTwo (events.js:87:13)
       at ChildProcess.emit (events.js:172:7)
       at handleMessage (internal/child_process.js:686:10)
       at Pipe.channel.onread (internal/child_process.js:440:11)
```
