### ISSUE TITLE
"Error: Must give hashtype string as argument" prevents build on change with hmr

### ISSUE THREAD

**Issue by ezmiller** [MoOx/eslint-loader#201]
I am trying to add eslint-loader to a webpack configuration tooled for hot reloading. When added the  webpack build process fails with an error when a file is changed:

```
webpack: Compiling...
crypto.js:56
  this._handle = new binding.Hash(algorithm);
                 ^

Error: Must give hashtype string as argument
    at Error (native)
    at new Hash (crypto.js:56:18)
    at Object.Hash (crypto.js:55:12)
    at Compilation.createHash (**/node_modules/webpack/lib/Compilation.js:1166:23)
    at sealPart2 (**/node_modules/webpack/lib/Compilation.js:620:9)
    at Compilation.applyPluginsAsyncSeries (**/node_modules/tapable/lib/Tapable.js:195:46)
    at Compilation.seal (/**/node_modules/webpack/lib/Compilation.js:580:8)
    at /**/node_modules/webpack/lib/Compiler.js:510:16
    at /**/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/**/node_modules/webpack/lib/Compilation.js:482:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! enzo-client@0.0.1 hot-assets: `webpack-dev-server --config ./webpack.hot.config.babel.js`
npm ERR! Exit status 1
```

I have a base webpack config that uses the following plugin/rules:

```
  ...
  plugins: [
    new webpack.DefinePlugin(envVars),
    new ModernizrWebpackPlugin(modernizrConfig),
  ],

  module: {
    rules: [
      {
        test: /\.(ttf|eot)$/,
        use: {
          loader: 'file-loader',
        },
      },
      {
        test: /\.(jpe?g|png|gif|svg)$/,
        use: {
          loader: 'url-loader?limit=8192'
        },
      },
    ],
  },
  ...
```

And then the hot reload config adds the following:
```
config.module.rules.push(
  {
    enforce: 'pre',
    test: /\.jsx?$/,
    exclude: /node_modules/,
    loader: 'eslint-loader',
    options: {
      // eslint-disable-next-line global-require
      formatter: require('eslint-friendly-formatter'),
    },
  },
  {
    test: /^(?!.*\.test\.js$).*\.jsx?$/,
    use: [
      'react-hot-loader/webpack',
      'babel-loader',
    ],
    exclude: /node_modules/,
  },
);

config.plugins.push(
  new webpack.optimize.CommonsChunkPlugin({
    name: 'vendor',
    filename: 'vendor-bundle.js',
    minChunks: Infinity,
  }),

  new webpack.HotModuleReplacementPlugin(),
  // enables HMR globally

  new webpack.NamedModulesPlugin(),
  // prints more readable module names in the browser console on HMR updates

  new webpack.NoEmitOnErrorsPlugin(),
  // do not emit compiled assets that include errors
);
```

Any idea what might be going on?

**Comment by MoOx** [comment]
Please share your node, npm & webpack version.

**Comment by ezmiller** [comment]
Sure:
* Node: v6.9.4
* npm: v5.2.0
* webpack: v3.0.0

**Comment by MoOx** [comment]
I have to admit I have no idea, sorry...

**Comment by ezmiller** [comment]
Okay, anyone else have any ideas?

**Comment by ezmiller** [comment]
I did a bit more digging here and found one clue. In the webpack file `webpack/lib/Compilation.js`, there are the following lines:
```
const outputOptions = this.outputOptions;
const hashFunction = outputOptions.hashFunction;
const hashDigest = outputOptions.hashDigest;
const hashDigestLength = outputOptions.hashDigestLength;
const hash = crypto.createHash(hashFunction);
```
The last shows up in the stack strace, and when I inspected the value of `hashFunction`, before the error, it was `undefined`.  The code, as you can see, tries to get the `hashFunction` from `outputOptions`, which seems to be a part of the config.

In the documentation for webpack 3, it says of `hashFunction` that it should default to `md5`. Looking at the outputOptions, the first time I start up webpack with hot-reload, it looks like this:

```
{ filename: '[name]-bundle.js',
  path: '/Users/***/Projects/***/enzo/client/public',
  publicPath: 'http://localhost:3500/',
  chunkFilename: '[id]-bundle.js',
  library: '',
  hotUpdateFunction: 'webpackHotUpdate',
  jsonpFunction: 'webpackJsonp',
  libraryTarget: 'var',
  sourceMapFilename: '[file].map[query]',
  hotUpdateChunkFilename: '[id].[hash].hot-update.js',
  hotUpdateMainFilename: '[hash].hot-update.json',
  crossOriginLoading: false,
  chunkLoadTimeout: 120000,
  hashFunction: 'md5',
  hashDigest: 'hex',
  hashDigestLength: 20,
  devtoolLineToLine: false,
  strictModuleExceptionHandling: false }
```
You can see that the `hashFunction` did default to 'md5'. When the recompilation process is triggered, it has somehow been stripped of most of these properties:
```
{ filename: '[name]-bundle.js',
  path: '/Users/***/Projects/***/***/app/assets/webpack' }
```

**Comment by MoOx** [comment]
Try using react-hot-loader/babel solution instead of webpack loader.

**Comment by ezmiller** [comment]
I was able to get this working by dropping my use of the 'eslint-import-resolver-wepback'.
