### ISSUE TITLE
webpack-dev-server crashes on js errors

### ISSUE THREAD

**Issue by SergeyKhval** [MoOx/eslint-loader#94]
```
/home/sergey/Documents/work/dashboard/node_modules/webpack-core/lib/NormalModuleMixin.js:163
			if(isError) throw e;
			            ^

Error: callback(): The callback was already called.
    at context.callback (/home/sergey/Documents/work/dashboard/node_modules/webpack-core/lib/NormalModuleMixin.js:143:11)
    at Object.module.exports (/home/sergey/Documents/work/dashboard/node_modules/eslint-loader/index.js:130:7)
    at WEBPACK_CORE_LOADER_EXECUTION (/home/sergey/Documents/work/dashboard/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/home/sergey/Documents/work/dashboard/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/home/sergey/Documents/work/dashboard/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /home/sergey/Documents/work/dashboard/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/sergey/Documents/work/dashboard/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/sergey/Documents/work/dashboard/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

Instead of showing js errors in the console, eslint just crashes. What other logs are needed to help resolve this issue?

**Comment by MoOx** [comment]
No idea. Did you solve this?

**Comment by SergeyKhval** [comment]
@MoOx, I suppose the problem was in conflicting versions of dependencies. Unfortunately I don't remember what exact packages had conflicts.

**Comment by MoOx** [comment]
So is this ok for you now?

**Comment by SergeyKhval** [comment]
Yeah, everything works fine
